language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "N2eCGVnKdVRiCx9oS5w1/oKFcJRBkRmhOApCE5Lq6ZDPK1TWOalehpq2ECF3l2rRR4eKWb5C0i+bBYbPvKNbYIDcIb4b7v2y+zhCYPVCCkWUzpaoFJDRbfE/tpq8J9ggykDkdRrMsMfhnQuhdXTQUGZJJ6I+OeYF0JCLjkJEJUQZmMMQtTQonbkT14eo9TUL9VeSXlZROkbXWi5tsNGAyT562+ceJsK/YuEc9vaTBz+J3SokFYd76ROIfGG6Zm6lMv2d0MMXWH0hS+d8cq3IEGTEI72x7xaeEE3JY0tytuX7QFhSPDxkj1HKCAOBxilnEfbSil++IKiYsPFbON7bUqNFyP3xicCZN5Qb+Nfd2vpbftCBokSUUSZ0BpgRPSVsNv/8Kdo01lWpxuAdcXjuh7ff1D8xucsCXYPypEpJ8v1QVpi+GHC2gDL8BG5oFxf9I23zlz/WJnPBNqkn8A9HZV1A9e1sXDOARG/yXo4UoIhLtyrdwtpuH/OZozZx9PFx/9ssUbYe4n7QZAvVoXHq64tZ8luUlTSTaKRqOahKlvt6RJAGdzwUo15dY2rFj2XTEGuUhwM0D1rpu/ZcRGJ8mfqc8Zctzdp4VOi4w+CEYkzYq3cW07RLbSRUmNKcmtqvlpvbOWoJS8+HTW1JJWD6xSIqwjfesWxTnOFh8E0zPYA="
